'use strict';

// wg-quick runs PostUp/PostDown as a single ';'-joined line under `set -e`, so a
// bare `iptables -D` for an already-absent rule aborts the rest of the chain
// (silently skipping every rule after it — notably the site-masq rule, rendered
// last), and a bare `iptables -A` re-appends on every `up`. Render each rule
// idempotently and self-healing instead: add only if missing, delete every copy
// without letting one failure abort the chain.
const addRule = (table, rule) => {
  const ipt = `iptables${table ? ` -t ${table}` : ''}`;
  return `${ipt} -C ${rule} 2>/dev/null || ${ipt} -A ${rule};`;
};
const delRule = (table, rule) => {
  const ipt = `iptables${table ? ` -t ${table}` : ''}`;
  return `while ${ipt} -C ${rule} 2>/dev/null; do ${ipt} -D ${rule} || break; done;`;
};

const siteMasqRules = (clients, device, mk) => Object.values(clients || {})
  .filter((c) => c.enabled && c.siteMasquerade && c.allowedIPs)
  .flatMap((c) => c.allowedIPs.split(',').map((s) => s.trim()).filter(Boolean)
    .map((cidr) => mk('nat', `POSTROUTING -s ${cidr} -o ${device} -j MASQUERADE`)))
  .join(' ');

const defaultHooks = (server, device, clients, mk) => [
  mk('nat', `POSTROUTING -s ${server.defaultAddress.replace('x', '0')}/24 -o ${device} -j MASQUERADE`),
  mk('', `INPUT -p udp -m udp --dport ${server.port} -j ACCEPT`),
  mk('', 'FORWARD -i wg0 -j ACCEPT'),
  mk('', 'FORWARD -o wg0 -j ACCEPT'),
  siteMasqRules(clients, device, mk),
].filter(Boolean).join(' ');

const defaultPostUp = (server, device, clients) => defaultHooks(server, device, clients, addRule);
const defaultPostDown = (server, device, clients) => defaultHooks(server, device, clients, delRule);

const pick = (override, fallback) => (typeof override === 'string' && override !== '' ? override : fallback);

function renderDefaultHooks(server, env = {}, clients = {}) {
  const device = env.device || 'eth0';
  return {
    preUp: pick(env.preUp, ''),
    postUp: pick(env.postUp, defaultPostUp(server, device, clients)),
    preDown: pick(env.preDown, ''),
    postDown: pick(env.postDown, defaultPostDown(server, device, clients)),
  };
}

function renderServerConf(server, clients, hooks, imitateProtocol) {
  let result = `
# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = ${server.privateKey}
Address = ${server.address}/24
ListenPort = ${server.port}
PreUp = ${hooks.preUp}
PostUp = ${hooks.postUp}
PreDown = ${hooks.preDown}
PostDown = ${hooks.postDown}
Jc = ${server.jc}
Jmin = ${server.jmin}
Jmax = ${server.jmax}
S1 = ${server.s1}
S2 = ${server.s2}
S3 = ${server.s3}
S4 = ${server.s4}
H1 = ${server.h1.min}-${server.h1.max}
H2 = ${server.h2.min}-${server.h2.max}
H3 = ${server.h3.min}-${server.h3.max}
H4 = ${server.h4.min}-${server.h4.max}
${imitateProtocol !== 'none' ? `ImitateProtocol = ${imitateProtocol}\n` : ''}`;

  for (const [clientId, client] of Object.entries(clients)) {
    if (!client.enabled) continue;
    result += `

# Client: ${client.name} (${clientId})
[Peer]
PublicKey = ${client.publicKey}
${client.preSharedKey ? `PresharedKey = ${client.preSharedKey}\n` : ''
}AllowedIPs = ${client.allowedIPs && client.allowedIPs.trim() ? client.allowedIPs : `${client.address}/32`}`;
  }
  return result;
}

function renderClientConf(server, client, imitateProtocol) {
  return `
[Interface]
PrivateKey = ${client.privateKey ? `${client.privateKey}` : 'REPLACE_ME'}
Address = ${client.address}
${server.dns ? `DNS = ${server.dns}\n` : ''}\
${server.mtu ? `MTU = ${server.mtu}\n` : ''}\
Jc = ${server.jc}
Jmin = ${server.jmin}
Jmax = ${server.jmax}
S1 = ${server.s1}
S2 = ${server.s2}
S3 = ${server.s3}
S4 = ${server.s4}
H1 = ${server.h1.min}-${server.h1.max}
H2 = ${server.h2.min}-${server.h2.max}
H3 = ${server.h3.min}-${server.h3.max}
H4 = ${server.h4.min}-${server.h4.max}
${imitateProtocol !== 'none' ? `ImitateProtocol = ${imitateProtocol}\n` : ''}\
${server.i1 ? `I1 = ${server.i1}\n` : ''}\
${server.i2 ? `I2 = ${server.i2}\n` : ''}\
${server.i3 ? `I3 = ${server.i3}\n` : ''}\
${server.i4 ? `I4 = ${server.i4}\n` : ''}\
${server.i5 ? `I5 = ${server.i5}\n` : ''}\

[Peer]
PublicKey = ${server.publicKey}
${client.preSharedKey ? `PresharedKey = ${client.preSharedKey}\n` : ''
}AllowedIPs = ${server.allowedIPs}
PersistentKeepalive = ${server.persistentKeepalive}
Endpoint = ${server.host}:${server.port}`;
}

module.exports = { renderDefaultHooks, renderServerConf, renderClientConf };
