'use strict';

const defaultPostUp = (server, device) => `
iptables -t nat -A POSTROUTING -s ${server.defaultAddress.replace('x', '0')}/24 -o ${device} -j MASQUERADE;
iptables -A INPUT -p udp -m udp --dport ${server.port} -j ACCEPT;
iptables -A FORWARD -i wg0 -j ACCEPT;
iptables -A FORWARD -o wg0 -j ACCEPT;
`.split('\n').join(' ');

const defaultPostDown = (server, device) => `
iptables -t nat -D POSTROUTING -s ${server.defaultAddress.replace('x', '0')}/24 -o ${device} -j MASQUERADE;
iptables -D INPUT -p udp -m udp --dport ${server.port} -j ACCEPT;
iptables -D FORWARD -i wg0 -j ACCEPT;
iptables -D FORWARD -o wg0 -j ACCEPT;
`.split('\n').join(' ');

const pick = (override, fallback) => (typeof override === 'string' && override !== '' ? override : fallback);

function renderDefaultHooks(server, env = {}) {
  const device = env.device || 'eth0';
  return {
    preUp: pick(env.preUp, ''),
    postUp: pick(env.postUp, defaultPostUp(server, device)),
    preDown: pick(env.preDown, ''),
    postDown: pick(env.postDown, defaultPostDown(server, device)),
  };
}

function renderServerConf(server, clients, hooks, imitateProtocol) {
  let result = `
# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = ${server.privateKey}
Address = ${server.address}/24
ListenPort = ${server.port}
PreUp = ${hooks.preUp}
PostUp = ${hooks.postUp}
PreDown = ${hooks.preDown}
PostDown = ${hooks.postDown}
Jc = ${server.jc}
Jmin = ${server.jmin}
Jmax = ${server.jmax}
S1 = ${server.s1}
S2 = ${server.s2}
S3 = ${server.s3}
S4 = ${server.s4}
H1 = ${server.h1.min}-${server.h1.max}
H2 = ${server.h2.min}-${server.h2.max}
H3 = ${server.h3.min}-${server.h3.max}
H4 = ${server.h4.min}-${server.h4.max}
${imitateProtocol !== 'none' ? `ImitateProtocol = ${imitateProtocol}\n` : ''}`;

  for (const [clientId, client] of Object.entries(clients)) {
    if (!client.enabled) continue;
    result += `

# Client: ${client.name} (${clientId})
[Peer]
PublicKey = ${client.publicKey}
${client.preSharedKey ? `PresharedKey = ${client.preSharedKey}\n` : ''
}AllowedIPs = ${client.address}/32`;
  }
  return result;
}

function renderClientConf(server, client, imitateProtocol) {
  return `
[Interface]
PrivateKey = ${client.privateKey ? `${client.privateKey}` : 'REPLACE_ME'}
Address = ${client.address}
${server.dns ? `DNS = ${server.dns}\n` : ''}\
${server.mtu ? `MTU = ${server.mtu}\n` : ''}\
Jc = ${server.jc}
Jmin = ${server.jmin}
Jmax = ${server.jmax}
S1 = ${server.s1}
S2 = ${server.s2}
S3 = ${server.s3}
S4 = ${server.s4}
H1 = ${server.h1.min}-${server.h1.max}
H2 = ${server.h2.min}-${server.h2.max}
H3 = ${server.h3.min}-${server.h3.max}
H4 = ${server.h4.min}-${server.h4.max}
${imitateProtocol !== 'none' ? `ImitateProtocol = ${imitateProtocol}\n` : ''}\
${server.i1 ? `I1 = ${server.i1}\n` : ''}\
${server.i2 ? `I2 = ${server.i2}\n` : ''}\
${server.i3 ? `I3 = ${server.i3}\n` : ''}\
${server.i4 ? `I4 = ${server.i4}\n` : ''}\
${server.i5 ? `I5 = ${server.i5}\n` : ''}\

[Peer]
PublicKey = ${server.publicKey}
${client.preSharedKey ? `PresharedKey = ${client.preSharedKey}\n` : ''
}AllowedIPs = ${server.allowedIPs}
PersistentKeepalive = ${server.persistentKeepalive}
Endpoint = ${server.host}:${server.port}`;
}

module.exports = { renderDefaultHooks, renderServerConf, renderClientConf };
